language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install numpy                                     
  - pip install python-speech-features                  
  - pip install scikit-learn                         
  - pip install scipy                                 
# command to run tests
script:
  - pytest
